server:
  port: 8080

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
#    username: root
#    password: pAssword
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-group
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.user service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
